import express from "express";
import path from "path";
import { ENV } from "./config/env.js";
import { connectDB } from "./config/db.js";
import { clerkMiddleware } from "@clerk/express";
import { serve } from "inngest/express";
import { functions, inngest } from "./config/inngest.js";
import { syncUser, deleteUserFromDB } from "./config/inngest.js";

import adminRoutes from "./routes/admin.route.js";
import userRoutes from "./routes/user.route.js";
import orderRoutes from "./routes/order.route.js";
import reviewRoutes from "./routes/review.route.js";
import productRoutes from "./routes/product.route.js";
import categoryRoutes from "./routes/category.route.js";
import carouselRoutes from "./routes/carousel.route.js";
import cartRoutes from "./routes/cart.route.js";
import promoBannerRoutes from "./routes/promoBanner.routes.js";
import paymentRoutes from "./routes/payment.route.js";
import { handleWebhook } from "./controllers/payment.controller.js";

import cors from "cors";  

const app = express();


// Get the full path of the current file
const __dirname = path.resolve();

// CRITICAL: Raw body parser for Stripe webhook MUST come before JSON parser
app.post(
  "/api/payment/webhook",
  express.raw({ type: "application/json" }),
  handleWebhook
);

//makes it possible to handle json data in the request body
app.use(express.json());

//makes it possible to handle form data (urlencoded) from admin panel
app.use(express.urlencoded({ extended: true }));

// Serve static files from Next.js public folder in development
if (ENV.NODE_ENV !== "production") {
  app.use("/images", express.static(path.join(__dirname, "../../nextjs-ecommerce-template/public/images")));
}

app.use(clerkMiddleware()); // adds auth object to request
app.use(cors({ 
  origin: [ENV.CLIENT_URL, ENV.WEBSITE_URL, "http://localhost:5000", "http://localhost:5173"], 
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));

// Mount payment routes for other endpoints
app.use("/api/payment", paymentRoutes);


// we got this from inngest documentation so there's no need to try to know it by heart
app.use(
  "/api/inngest",
  serve({ client: inngest, functions:[ syncUser, deleteUserFromDB], streaming: "force", }),
);

app.use("/api/admin",adminRoutes)
app.use("/api/users",userRoutes)
app.use("/api/orders", orderRoutes);
app.use("/api/reviews", reviewRoutes);
app.use("/api/products", productRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/carousels", carouselRoutes);
app.use("/api/cart", cartRoutes);
app.use("/api/promo-banners", promoBannerRoutes);



app.get("/api/health", (req, res) => {
  res.status(200).json({ message: "success" });
});

// make our app ready forz deployment
if (ENV.NODE_ENV === "production") {
  // what we are doing is taking the dist folder generated by npm run build and making it our static folder, which is the frontend of our application
  app.use(express.static(path.join(__dirname, "../admin/dist")));

  // if we visit any routes other than our api routes we would like to see our application
  app.get("/{*any}", (req, res) => {
    res.sendFile(path.join(__dirname, "../admin/dist", "index.html"));
  });
}

const startServer = async () => {
  await connectDB();
  app.listen(ENV.PORT, () => {
    console.log("Server is up and running");
  });
};

startServer();
