import express from "express";
import path from "path";
import { ENV } from "./config/env.js";
import { connectDB } from "./config/db.js";
import { clerkMiddleware } from "@clerk/express";
import { serve } from "inngest/express";
import { functions, inngest } from "./config/inngest.js";

const app = express();

// Get the full path of the current file
const __dirname = path.resolve();

// we got this from inngest documentation so there's no need to try to know it by heart
app.use(
  "/api/inngest",
  express.raw({ type: "application/json" }),
  serve({ client: inngest, functions })
);

//makes it possible to handle json data in the request body
app.use(express.json());
app.use(clerkMiddleware()); // adds auth object to request

app.get("/api/health", (req, res) => {
  res.status(200).json({ message: "success" });
});

// make our app ready for deployment
if (ENV.NODE_ENV === "production") {
  // what we are doing is taking the dist folder generated by npm run build and making it our static folder, which is the frontend of our application
  app.use(express.static(path.join(__dirname, "../admin/dist")));

  // if we visit any routes other than our api routes we would like to see our application
  app.get("/{*any}", (req, res) => {
    res.sendFile(path.join(__dirname, "../admin/dist", "index.html"));
  });
}

const startServer = async () => {
  await connectDB();
  app.listen(ENV.PORT, () => {
    console.log("Server is up and running");
  });
};

startServer();
